"""Shared defaults for bounded symbolic MIDI experiments."""

from __future__ import annotations

SEED = 253

DEFAULT_BLOCK_SIZE = 64
DEFAULT_STRIDE = 32
DEFAULT_VALID_FRACTION = 0.2

DEFAULT_MARKOV_ORDER = 3

DEFAULT_TRANSFORMER_EMBED = 64
DEFAULT_TRANSFORMER_LAYERS = 2
DEFAULT_TRANSFORMER_HEADS = 2
DEFAULT_TRANSFORMER_BATCH_SIZE = 16
DEFAULT_TRANSFORMER_EPOCHS = 2
DEFAULT_TRANSFORMER_MAX_STEPS = 80
DEFAULT_TRANSFORMER_LR = 3e-4

DEFAULT_GENERATE_TOKENS = 192
DEFAULT_TEMPERATURE = 1.0
DEFAULT_TOP_K = 20
